### ISSUE TITLE
error: no matching function for call to ‘RoverRobotics::ProProtocolObject::ProProtocolObject(const char*, std::__cxx11::basic_string<char>&, bool&, RoverRobotics::PidGains&)’

### ISSUE THREAD

**Issue by lin123-stack** [RoverRobotics/roverrobotics_ros2_archive#12]
I met the problem when rebuild ,how to solves it? thank you

**Comment by drhieu** [comment]
hi, Is this because you are rebuilding from a fresh computer?
RoverRobotics::ProPtocolObject is a part of librover. As long as you have librover installed this error shouldn't be there.
https://github.com/roverrobotics/librover

**Comment by CollinNHays** [comment]
I have installed librover as according the instructions. I am running into this same issue on both Ubuntu 20.04 and 18.04.

**Comment by CollinNHays** [comment]
Looking closer into the code. This may be a type mismatch between enum (0-2) robot_motion_mode and bool closed_loop

**Comment by drhieu** [comment]
Can you link console logs; or code where enum are mismatched?
Even if enum mismatching; it shouldn't cause the function objects to show that error

**Comment by CollinNHays** [comment]
![rover](https://user-images.githubusercontent.com/87328641/131561737-4e12451b-d428-4085-ac68-0c792219eaed.png)

I was able to get this Ros2 driver to compile by using an older version of librover from 6 months ago linked below.
https://github.com/RoverRobotics/librover/tree/37680bc89d1efdf1acabf195904dd2e846cc1f28

**Comment by drhieu** [comment]
Is everything in your repository is up to date? We updated our cmake to a higher version with a higher C++ standard requirement. The first thing I saw from your console output is that the std::optional is missing, which should've been included as part of the new standard

**Comment by CollinNHays** [comment]
Everything is up to date. I am getting this same error on both a fresh install of Ubuntu 20.04 with cmake 3.16.3 and on Ununtu 18.04 with cmake 3.21.

It looks pretty clear to me that the latest version of librover is not compatible with the current version of this ROS2 driver.

**Comment by drhieu** [comment]
is your Cmake file checking for C++17/21 standards?

**Comment by CollinNHays** [comment]
I'm not exactly sure how to check this, however I am also running into this error on a machine with a fresh install of Ubuntu 20.04 with ros2 foxy cmake 3.16.3.

**Comment by jackarivera** [comment]
Closing due to being over a year old with no updates. If this is still an issue, please reopen a new issue with problem details.
