### ISSUE TITLE
 Rover Pro rpm suddenly changes to a negative value

### ISSUE THREAD

**Issue by shoemakerlevy9** [RoverRobotics/roverrobotics_ros2_archive#14]
The rpm received from UART suddenly changes to a negative value when speed of 1.6m/s or more is passed to the topic of cmd_vel.

We think that Rover Pro will send an invalid rpm when the motor speed exceeds the maximum value of 32,767 of "signed unsigned char" type

```
[protocol_pro.cpp]
void ProProtocolObject::unpack_comm_response(std::vector<uint8_t> robotmsg) {
..
int16_t b = (data1 << 8) + data2;
switch (int(dataNO)) {
case REG_PWR_TOTAL_CURRENT:
break;
case REG_MOTOR_FB_RPM_LEFT:
robotstatus_.motor1_rpm = b;
RCLCPP_INFO(rclcpp::get_logger("librover"), "motor1 : %d", robotstatus_.motor1_rpm); <== HERE
break;
case REG_MOTOR_FB_RPM_RIGHT: // motor2_rpm;
robotstatus_.motor2_rpm = b;
RCLCPP_INFO(rclcpp::get_logger("librover"), "motor2 : %d", robotstatus_.motor2_rpm); <== HERE
break;
```

[roverrobotics_driver-2] [INFO] [1627352670.935052496] [librover]: write 253 215 215 125 10 2 198
[roverrobotics_driver-2] [INFO] [1627352670.936004152] [librover]: write 253 215 215 125 10 4 196
[roverrobotics_driver-2] [INFO] [1627352670.947495799] [librover]: motor1 : 27758
[roverrobotics_driver-2] [INFO] [1627352670.947623064] [librover]: motor2 : 24019
[roverrobotics_driver-2] [INFO] [1627352670.969478827] [librover]: write 253 214 216 125 10 2 198
[roverrobotics_driver-2] [INFO] [1627352670.970326930] [librover]: write 253 214 216 125 10 4 196
[roverrobotics_driver-2] [INFO] [1627352670.979489694] [librover]: motor1 : 24019
[roverrobotics_driver-2] [INFO] [1627352670.979624927] [librover]: motor2 : -32661 <==Here is the issue log!!

**Comment by drhieu** [comment]
This is the wrong place to put this since it is related to librover and not Roverrobotics ROS2.

**Comment by drhieu** [comment]
Is this same issue happens in Roverrobotics ROS1 as well ?

**Comment by shoemakerlevy9** [comment]
@drhieu don't know. Can you recreate the issue on the librover repo?

**Comment by drhieu** [comment]
@shoemakerlevy9 the data looks like it is signed already so it shouldn't do that Unless the data coming back from the Firmware of the robot is overflowing. Do you know which version of the firmware the robot is running.

**Comment by drhieu** [comment]
Definitely an overflow. since the data coming from the robot firmware is only 2-Byte, which range -32,768 to 32,767. None of our message from the firmware is sending more than 2-Byte at the moment; We should do a Firmware Update and Software Update to deal with this.
