### ISSUE TITLE
 roverrobotics_ros2_b  package?

### ISSUE THREAD

**Issue by SteveMacenski** [RoverRobotics/roverrobotics_ros2_archive#2]
Seems like an old artifact, should this metapackage be removed or renamed? Given the number of packages in here, I might suggest removing it for now and readding a metapackage if/when you have more `roverrobotics_*` packages (like nav configurations, etc)

**Comment by SteveMacenski** [comment]
and in readme instructions

**Comment by drhieu** [comment]
updated in PR #9. Metapackage is removed

**Comment by jbrover** [comment]
closing as addressed in PR #9
