### ISSUE TITLE
Rover Zero 3 Compatibility

### ISSUE THREAD

**Issue by rcarnemollaBE** [RoverRobotics/roverrobotics_ros2_archive#22]
Is the Zero 3 ROS2 compatible? I have followed the installation and communication instructions found here and in the tools repository, but I have been unable to connect to the robot when using the zero2.launch.py file. I installed the tools for Rover Zero 2, as this was seemingly the closest model to the Zero 3, which I am using.

**Comment by jackarivera** [comment]
Yes. The zero2 install should work fine. I will add a specific zero3 to the install script. If you run into any issues with using the zero2 install post them here and I will take a look at them asap.

**Comment by gseqBE** [comment]
Thanks @jackarivera 
However there seems to be an issue with the zero 3. The driver gets the initial handle to the port, registered by the udev rule, but then disconnects. It seems that the driver connects initially, but then is_connected gets to false, before publish_robot_info() can receive a response from the bot.


[INFO] [launch]: All log files can be found below /home/be/.ros/log/2022-11-30-15-05-33-509862-be-LattePanda-Delta-53171
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [roverrobotics_driver-1]: process started with pid [53173]
[roverrobotics_driver-1] [INFO] [1669838733.783221002] [roverrobotics_driver]: Starting Rover Driver node
[roverrobotics_driver-1] [INFO] [1669838733.785585346] [roverrobotics_driver]: Robot type is Rover zero2 over serial
[roverrobotics_driver-1] [INFO] [1669838733.785633925] [roverrobotics_driver]: Receiving velocity command from /cmd_vel
[roverrobotics_driver-1] [INFO] [1669838733.785651106] [roverrobotics_driver]: Estop state is currently inactive
[roverrobotics_driver-1] [INFO] [1669838733.785664318] [roverrobotics_driver]: Receiving Estop activation at /soft_estop/trigger
[roverrobotics_driver-1] [INFO] [1669838733.785679037] [roverrobotics_driver]: Receiving Estop deactivation at /soft_estop/reset
[roverrobotics_driver-1] [INFO] [1669838733.794064183] [roverrobotics_driver]: Publishing Robot TF on /odom_raw at 15.00hz
[roverrobotics_driver-1] [INFO] [1669838733.798483658] [roverrobotics_driver]: Publishing Robot status on /robot_status at 60.00hz
[roverrobotics_driver-1] [INFO] [1669838733.798561543] [roverrobotics_driver]: Closed Loop Control is Disabled and Control Mode is in OPEN LOOP
[roverrobotics_driver-1] [INFO] [1669838733.798578748] [roverrobotics_driver]: PID is at P:0.0011 I:0.0000 D:0.0001
[roverrobotics_driver-1] [INFO] [1669838733.798599598] [roverrobotics_driver]: Attempting to connect to robot at /dev/rover-zero-v2
[roverrobotics_driver-1] protocol is running...
[roverrobotics_driver-1] [INFO] [1669838733.801937065] [roverrobotics_driver]: Connected to robot at /dev/rover-zero-v2
[roverrobotics_driver-1] [INFO] [1669838733.802021796] [roverrobotics_driver]: Use 'ros2 param dump /roverrobotics_driver --print' to print see all parameters running on this node
[roverrobotics_driver-1] [FATAL] [1669838733.815507068] [roverrobotics_driver]: Didn't receive data from the Robot. Stopping this Driver Node
[INFO] [roverrobotics_driver-1]: process has finished cleanly [pid 53173]

**Comment by bgeisel1** [comment]
@jackarivera I'll follow @gseqBE 's comment with a me too and a little additional data. I was able to alter debug.cpp in librover and I do get data out of the robot, if I move the wheels, I see velocity values I expect, etc.

However, I'm getting the same issue with Zero3 as above, the ROS2 driver doesn't seem to like it. Dump below, but it's almost identical to the one above.

Thanks!

[roverrobotics_driver-1] [INFO] [1673897440.807689508] [roverrobotics_driver]: Starting Rover Driver node
[roverrobotics_driver-1] [INFO] [1673897440.808799640] [roverrobotics_driver]: Robot type is Rover zero2 over serial
[roverrobotics_driver-1] [INFO] [1673897440.809149114] [roverrobotics_driver]: Receiving velocity command from /cmd_vel
[roverrobotics_driver-1] [INFO] [1673897440.809453919] [roverrobotics_driver]: Estop state is currently inactive
[roverrobotics_driver-1] [INFO] [1673897440.809753234] [roverrobotics_driver]: Receiving Estop activation at /soft_estop/trigger
[roverrobotics_driver-1] [INFO] [1673897440.810055273] [roverrobotics_driver]: Receiving Estop deactivation at /soft_estop/reset
[roverrobotics_driver-1] [INFO] [1673897440.825142894] [roverrobotics_driver]: Publishing Robot TF on /odom_raw at 15.00hz
[roverrobotics_driver-1] [INFO] [1673897440.827623277] [roverrobotics_driver]: Publishing Robot status on /robot_status at 60.00hz
[roverrobotics_driver-1] [INFO] [1673897440.828215671] [roverrobotics_driver]: Closed Loop Control is Disabled and Control Mode is in OPEN LOOP
[roverrobotics_driver-1] [INFO] [1673897440.828545457] [roverrobotics_driver]: PID is at P:0.0011 I:0.0000 D:0.0001
[roverrobotics_driver-1] [INFO] [1673897440.828852451] [roverrobotics_driver]: Attempting to connect to robot at /dev/rover-zero-v2
[roverrobotics_driver-1] protocol is running...
[roverrobotics_driver-1] [INFO] [1673897440.831592875] [roverrobotics_driver]: Connected to robot at /dev/rover-zero-v2
[roverrobotics_driver-1] [INFO] [1673897440.831612600] [roverrobotics_driver]: Use 'ros2 param dump /roverrobotics_driver --print' to print see all parameters running on this node
[roverrobotics_driver-1] [FATAL] [1673897440.851884590] [roverrobotics_driver]: Didn't receive data from the Robot. Stopping this Driver Node
[INFO] [roverrobotics_driver-1]: process has finished cleanly [pid 1425747]

**Comment by RoverRoboticsProduction** [comment]
We are aware of this issue and are attempting to resolve it, it appears to be some sort of communication issue with FTDI. In the meantime we have a workaround. Inside the robot on the motor controller there are micro USB slots, if you connect to the motor controller via micro USB instead of the installed FTDI, ROS2 is able to establish communication. If you are not sure how to make that change yourself you can [contact us here](https://roverrobotics.com/pages/support-form) for support.
