### ISSUE TITLE
udev naming convention

### ISSUE THREAD

**Issue by SteveMacenski** [RoverRobotics/roverrobotics_ros2_archive#3]
https://github.com/RoverRobotics/roverrobotics_ros2/tree/main/roverrobotics_driver/udev udev rules by convention start with a number between (I believe) 1 and 99 rated by importance. This numbering is important in case of colliding udev rules such that the highest priority rules override lower ones in case of conflict. May I suggest something in the mid-30s to 60s.

**Comment by drhieu** [comment]
updating with PR #9 Udev now will be 50-

**Comment by SteveMacenski** [comment]
https://github.com/RoverRobotics/roverrobotics_ros2/tree/05410566dfd83a959345753c6d86352d4bdf6bc6/roverrobotics_driver/udev

Please also update your raw file name

**Comment by drhieu** [comment]
will do!
