### ISSUE TITLE
Check for valid connection before entering loops / timers / subscriber callbacks

### ISSUE THREAD

**Issue by SteveMacenski** [RoverRobotics/roverrobotics_ros2_archive#6]
To make sure the data is valid before publishing things so that if there's a connection error, you know before being able to continue with startup.

**Comment by SteveMacenski** [comment]
Lifecycle nodes would help with this to make sure you have things setup well in `configure` but you could do a similar thing without the formality if lifecycle nodes if you can handle the initialization state better

**Comment by drhieu** [comment]
PR #9 should address this.
